
import { LacanRealm, StarMapping, StarCategory } from './types';

export const STAR_DATA: StarMapping[] = [
  // --- 14 Main Stars (14主星) ---
  {
    id: 'ziwei',
    name: '紫微',
    pinyin: 'Zi Wei',
    category: StarCategory.MAIN,
    realm: LacanRealm.SYMBOLIC,
    lacanConcept: '大它者 (The Big Other)',
    description: '象征秩序的核心，作为律法之源的主体参照点。',
    traditionalMeaning: '帝座，至尊，代表领导力与尊贵。',
    philosophicalInsight: '紫微是象征界的锚点，主体试图通过认同它来获得身份的合法性。',
    color: '#a855f7'
  },
  {
    id: 'tianji',
    name: '天机',
    pinyin: 'Tian Ji',
    category: StarCategory.MAIN,
    realm: LacanRealm.SYMBOLIC,
    lacanConcept: '能指链的滑动',
    description: '思维的流转，象征系统中不断变动的逻辑。',
    traditionalMeaning: '智多星，善变，代表智慧与机巧。',
    philosophicalInsight: '智慧并非真相，而是能指在系统中的无尽延宕与替换。',
    color: '#3b82f6'
  },
  {
    id: 'taiyang',
    name: '太阳',
    pinyin: 'Tai Yang',
    category: StarCategory.MAIN,
    realm: LacanRealm.IMAGINARY,
    lacanConcept: '理想自我 (Ideal-Ego)',
    description: '在镜像阶段通过他者目光构建的完美形象。',
    traditionalMeaning: '光明，显赫，博爱，代表社会成就。',
    philosophicalInsight: '太阳的灼热是认同的眩光，掩盖了主体内在的匮乏。',
    color: '#fbbf24'
  },
  {
    id: 'wuqu',
    name: '武曲',
    pinyin: 'Wu Qu',
    category: StarCategory.MAIN,
    realm: LacanRealm.IMAGINARY,
    lacanConcept: '想象的防御 (Imaginary Armor)',
    description: '对物质力量的执着，是主体抵御虚无的坚硬外壳。',
    traditionalMeaning: '财星，刚毅，决断，代表财富与执行力。',
    philosophicalInsight: '武曲象征主体在物质世界寻找的支点，防止其滑向实在界的焦虑。',
    color: '#94a3b8'
  },
  {
    id: 'tiantong',
    name: '天同',
    pinyin: 'Tian Tong',
    category: StarCategory.MAIN,
    realm: LacanRealm.IMAGINARY,
    lacanConcept: '原初享乐 (Original Jouissance)',
    description: '对母体融合与零度张力的退行性渴望。',
    traditionalMeaning: '福星，慵懒，孩子气，代表享乐。',
    philosophicalInsight: '天同是主体对“失去的乐园”的不断回溯，拒绝象征界的劳动。',
    color: '#2dd4bf'
  },
  {
    id: 'lianzhen',
    name: '廉贞',
    pinyin: 'Lian Zhen',
    category: StarCategory.MAIN,
    realm: LacanRealm.SYMBOLIC,
    lacanConcept: '欲望与禁忌的张力',
    description: '超我的严苛与欲望的放逐在象征秩序边缘的博弈。',
    traditionalMeaning: '囚星，邪星，纪律，次桃花。',
    philosophicalInsight: '廉贞展示了象征秩序如何通过禁忌（囚）来维持欲望的生命力。',
    color: '#ef4444'
  },
  {
    id: 'tianfu',
    name: '天府',
    pinyin: 'Tian Fu',
    category: StarCategory.MAIN,
    realm: LacanRealm.IMAGINARY,
    lacanConcept: '自我的容器',
    description: '稳固的防御机制，试图通过积累来填补本体论的空洞。',
    traditionalMeaning: '库房，稳重，包容，代表守成。',
    philosophicalInsight: '天府是自我（Ego）构建的避风港，用符号资产抵御虚无。',
    color: '#f97316'
  },
  {
    id: 'taiyin',
    name: '太阴',
    pinyin: 'Tai Yin',
    category: StarCategory.MAIN,
    realm: LacanRealm.IMAGINARY,
    lacanConcept: '幻想空间 (Phantasy)',
    description: '私密的、柔和的映射，为主体提供栖息的幻景。',
    traditionalMeaning: '母性，宁静，田宅，代表潜意识中的安全感。',
    philosophicalInsight: '太阴是那面能映出温情的魔镜，它是主体避开实在界恐怖的屏幕。',
    color: '#818cf8'
  },
  {
    id: 'tanlang',
    name: '贪狼',
    pinyin: 'Tan Lang',
    category: StarCategory.MAIN,
    realm: LacanRealm.IMAGINARY,
    lacanConcept: '小客体a (Objet Petit a)',
    description: '欲望的诱因，那永远无法企及的、在缺失处闪烁的对象。',
    traditionalMeaning: '桃花，贪欲，修道，代表生命的原动力。',
    philosophicalInsight: '贪狼不代表欲望的对象，而代表欲望本身作为动力的“匮乏”。',
    color: '#ec4899'
  },
  {
    id: 'jumen',
    name: '巨门',
    pinyin: 'Ju Men',
    category: StarCategory.MAIN,
    realm: LacanRealm.REAL,
    lacanConcept: '能指的深渊 (The Abyss of the Signifier)',
    description: '言语无法填补的空穴，是焦虑与怀疑的源头。',
    traditionalMeaning: '暗星，口舌，疑虑，代表不可言说之物。',
    philosophicalInsight: '巨门是实在界的入侵，是象征秩序中那道“漏气”的裂缝。',
    color: '#4b5563'
  },
  {
    id: 'tianxiang',
    name: '天相',
    pinyin: 'Tian Xiang',
    category: StarCategory.MAIN,
    realm: LacanRealm.SYMBOLIC,
    lacanConcept: '镜像识别与契约',
    description: '辅助权威的官样文章，是象征秩序得以契合的胶水。',
    traditionalMeaning: '印星，协调，文书，代表公正与形式感。',
    philosophicalInsight: '天相通过形式的完美（印章），试图掩盖结构性的缺陷。',
    color: '#06b6d4'
  },
  {
    id: 'tianliang',
    name: '天梁',
    pinyin: 'Tian Liang',
    category: StarCategory.MAIN,
    realm: LacanRealm.SYMBOLIC,
    lacanConcept: '超我的父性保护',
    description: '通过建立道德律法与牺牲来缓解主体的原罪感。',
    traditionalMeaning: '荫星，老人，纪律，代表保护与解厄。',
    philosophicalInsight: '天梁是文明赋予个体的道德屏障，是象征秩序的柔性监护。',
    color: '#84cc16'
  },
  {
    id: 'qisha',
    name: '七杀',
    pinyin: 'Qi Sha',
    category: StarCategory.MAIN,
    realm: LacanRealm.REAL,
    lacanConcept: '死驱力 (Death Drive)',
    description: '对象征秩序的毁灭性突破，直接面对生命的荒诞真相。',
    traditionalMeaning: '将星，肃杀，变革，代表不破不立。',
    philosophicalInsight: '七杀是主体抛弃所有象征面具，直面“它者不存在”的瞬间。',
    color: '#b91c1c'
  },
  {
    id: 'pojun',
    name: '破军',
    pinyin: 'Po Jun',
    category: StarCategory.MAIN,
    realm: LacanRealm.REAL,
    lacanConcept: '付诸行动 (Passage to the Act)',
    description: '通过彻底的耗散与破坏来否定象征界的统治。',
    traditionalMeaning: '耗星，先锋，重建，代表彻底的变革。',
    philosophicalInsight: '破军是以主体的自我湮灭为代价，向实在界发起的主动进攻。',
    color: '#1e3a8a'
  },

  // --- 14 Assistant Stars (14辅星: 6 Lucky + 6 Malefic + 2 Misc) ---
  {
    id: 'zuofu',
    name: '左辅',
    pinyin: 'Zuo Fu',
    category: StarCategory.ASSISTANT,
    realm: LacanRealm.IMAGINARY,
    lacanConcept: '镜像认同 (Specular Identification)',
    description: '来自同伴的支持，强化自我的虚幻统一感。',
    traditionalMeaning: '平辈助力，稳健，代表环境的协同。',
    philosophicalInsight: '左辅通过“他者”的镜映，修补了主体的支离破碎感。',
    color: '#a5f3fc'
  },
  {
    id: 'youbi',
    name: '右弼',
    pinyin: 'You Bi',
    category: StarCategory.ASSISTANT,
    realm: LacanRealm.IMAGINARY,
    lacanConcept: '自我理想的投射',
    description: '对自我能力延伸的幻想性肯定。',
    traditionalMeaning: '异性助力，机智，代表隐秘的支援。',
    philosophicalInsight: '右弼是自我在其社交网络中投射出的“辅助性幻象”。',
    color: '#a78bfa'
  },
  {
    id: 'wenchang',
    name: '文昌',
    pinyin: 'Wen Chang',
    category: StarCategory.ASSISTANT,
    realm: LacanRealm.SYMBOLIC,
    lacanConcept: '主人能指 (S1)',
    description: '白纸黑字的律法，是象征秩序中被赋予权威的文字。',
    traditionalMeaning: '科甲，文书，正规教育，代表功名。',
    philosophicalInsight: '文昌是进入象征界的入场券，它是真理的符号化。',
    color: '#60a5fa'
  },
  {
    id: 'wenqu',
    name: '文曲',
    pinyin: 'Wen Qu',
    category: StarCategory.ASSISTANT,
    realm: LacanRealm.SYMBOLIC,
    lacanConcept: '知识的享乐 (S2)',
    description: '感性的流转，是象征链条中关于艺术与感性的知识。',
    traditionalMeaning: '口才，才艺，非传统学问，代表灵感。',
    philosophicalInsight: '文曲是能指链条的节奏与韵律，是理性的诗意化。',
    color: '#34d399'
  },
  {
    id: 'tiankui',
    name: '天魁',
    pinyin: 'Tian Kui',
    category: StarCategory.ASSISTANT,
    realm: LacanRealm.SYMBOLIC,
    lacanConcept: '理想它者 (Ideal Other)',
    description: '象征秩序中仁慈的引导力量。',
    traditionalMeaning: '贵人，明助，代表外部环境的垂青。',
    philosophicalInsight: '天魁是主体潜意识中对一个“全知全能且仁慈的父性”的渴望。',
    color: '#fbbf24'
  },
  {
    id: 'tianyue',
    name: '天钺',
    pinyin: 'Tian Yue',
    category: StarCategory.ASSISTANT,
    realm: LacanRealm.SYMBOLIC,
    lacanConcept: '象征界的机遇',
    description: '在象征秩序的缝隙中闪现的机会。',
    traditionalMeaning: '贵人，暗助，代表突如其来的转机。',
    philosophicalInsight: '天钺是象征界对主体的偶尔奖赏，缓解了结构的压抑。',
    color: '#f472b6'
  },
  {
    id: 'qingyang',
    name: '擎羊',
    pinyin: 'Qing Yang',
    category: StarCategory.ASSISTANT,
    realm: LacanRealm.REAL,
    lacanConcept: '阉割之刃 (Castration)',
    description: '粗暴的分离与切断，是进入象征界必须付出的创伤性代价。',
    traditionalMeaning: '刑伤，冲动，刚烈，代表痛苦的磨砺。',
    philosophicalInsight: '擎羊是那道划开主体与原初享乐的致命一刀。',
    color: '#dc2626'
  },
  {
    id: 'tuoluo',
    name: '陀罗',
    pinyin: 'Tuo Luo',
    category: StarCategory.ASSISTANT,
    realm: LacanRealm.REAL,
    lacanConcept: '症状的螺旋 (The Symptom Loop)',
    description: '主体在创伤周围不断的、强迫性的重复循环。',
    traditionalMeaning: '拖延，暗伤，纠结，代表挥之不去的阻碍。',
    philosophicalInsight: '陀罗是死驱力在象征界的一种体现：永无止境的循环往复。',
    color: '#64748b'
  },
  {
    id: 'huoxing',
    name: '火星',
    pinyin: 'Huo Xing',
    category: StarCategory.ASSISTANT,
    realm: LacanRealm.REAL,
    lacanConcept: '享乐的爆发 (Eruption of Jouissance)',
    description: '不可控的情绪与破坏力，是实在界最原始的能量喷发。',
    traditionalMeaning: '暴躁，动荡，突发事件，代表毁灭性的速度。',
    philosophicalInsight: '火星是主体瞬间失去对语言控制的时刻。',
    color: '#f97316'
  },
  {
    id: 'lingxing',
    name: '铃星',
    pinyin: 'Ling Xing',
    category: StarCategory.ASSISTANT,
    realm: LacanRealm.REAL,
    lacanConcept: '超我的回响 (Superego Echo)',
    description: '内在的、挥之不去的、隐秘的自我惩罚机制。',
    traditionalMeaning: '阴沉，焦虑，隐患，代表持续的心灵压力。',
    philosophicalInsight: '铃星是超我那永不停息的、尖锐的指责。',
    color: '#4338ca'
  },
  {
    id: 'dikong',
    name: '地空',
    pinyin: 'Di Kong',
    category: StarCategory.ASSISTANT,
    realm: LacanRealm.REAL,
    lacanConcept: '原初匮乏 (The Void)',
    description: '主体核心处的那个结构性黑洞。',
    traditionalMeaning: '空亡，精神性，虚幻，代表物质层面的消解。',
    philosophicalInsight: '地空揭示了欲望的核心并非任何对象，而是空无本身。',
    color: '#0f172a'
  },
  {
    id: 'dijie',
    name: '地劫',
    pinyin: 'Di Jie',
    category: StarCategory.ASSISTANT,
    realm: LacanRealm.REAL,
    lacanConcept: '欲望的截断 (Interruption)',
    description: '对幻想屏幕的粗暴撕裂，暴露出实在界的荒凉。',
    traditionalMeaning: '破财，劫难，波折，代表努力的无果。',
    philosophicalInsight: '地劫是主体在追逐幻想时，突然遭遇“它者并不存在”的瞬间。',
    color: '#451a03'
  },
  {
    id: 'lucun',
    name: '禄存',
    pinyin: 'Lu Cun',
    category: StarCategory.ASSISTANT,
    realm: LacanRealm.IMAGINARY,
    lacanConcept: '剩余享乐 (Plus-de-jouir)',
    description: '支撑主体活下去的那份盈余，是驱动机器运转的润滑油。',
    traditionalMeaning: '财禄，稳固，自私，代表生存的基础保障。',
    philosophicalInsight: '禄存是主体试图抓住的那一点点维持平衡的“多余”。',
    color: '#fb7185'
  },
  {
    id: 'tianma',
    name: '天马',
    pinyin: 'Tian Ma',
    category: StarCategory.ASSISTANT,
    realm: LacanRealm.SYMBOLIC,
    lacanConcept: '转喻的运动 (Metonymic Flow)',
    description: '欲望从一个能指不断跳跃到另一个能指的无止境过程。',
    traditionalMeaning: '奔波，变动，机会，代表生命力的位移。',
    philosophicalInsight: '天马是欲望的引擎，它永远在路上，拒绝任何终点的停靠。',
    color: '#fbbf24'
  }
];
