
import { LacanRealm, StarMapping, StarCategory } from './types';

export const STAR_DATA: StarMapping[] = [
  // --- 14 Main Stars (14主星) ---
  {
    id: 'ziwei',
    name: '紫微',
    pinyin: 'Zi Wei',
    category: StarCategory.MAIN,
    realm: LacanRealm.SYMBOLIC,
    lacanConcept: '大它者 (The Big Other)',
    description: '象征秩序的核心，作为律法之源的主体参照点。',
    traditionalMeaning: '帝座，至尊，代表领导力与尊贵。',
    philosophicalInsight: '紫微是象征界的锚点，主体试图通过认同它来获得身份的合法性。',
    color: '#a855f7'
  },
  {
    id: 'tianji',
    name: '天机',
    pinyin: 'Tian Ji',
    category: StarCategory.MAIN,
    realm: LacanRealm.SYMBOLIC,
    lacanConcept: '能指链的滑动',
    description: '思维的流转，象征系统中不断变动的逻辑。',
    traditionalMeaning: '智多星，善变，代表智慧与机巧。',
    philosophicalInsight: '智慧并非真相，而是能指在系统中的无尽延宕与替换。',
    color: '#3b82f6'
  },
  {
    id: 'taiyang',
    name: '太阳',
    pinyin: 'Tai Yang',
    category: StarCategory.MAIN,
    realm: LacanRealm.IMAGINARY,
    lacanConcept: '理想自我 (Ideal-Ego)',
    description: '在镜像阶段通过他者目光构建的完美形象。',
    traditionalMeaning: '光明，显赫，博爱，代表社会成就。',
    philosophicalInsight: '太阳的灼热是认同的眩光，掩盖了主体内在的匮乏。',
    color: '#fbbf24'
  },
  {
    id: 'wuqu',
    name: '武曲',
    pinyin: 'Wu Qu',
    category: StarCategory.MAIN,
    realm: LacanRealm.IMAGINARY,
    lacanConcept: '想象的防御 (Imaginary Armor)',
    description: '对物质力量的执着，是主体抵御虚无的坚硬外壳。',
    traditionalMeaning: '财星，刚毅，决断，代表财富与执行力。',
    philosophicalInsight: '武曲象征主体在物质世界寻找的支点，防止其滑向实在界的焦虑。',
    color: '#94a3b8'
  },
  {
    id: 'tiantong',
    name: '天同',
    pinyin: 'Tian Tong',
    category: StarCategory.MAIN,
    realm: LacanRealm.IMAGINARY,
    lacanConcept: '原初享乐 (Original Jouissance)',
    description: '对母体融合与零度张力的退行性渴望。',
    traditionalMeaning: '福星，慵懒，孩子气，代表享乐。',
    philosophicalInsight: '天同是主体对“失去的乐园”的不断回溯，拒绝象征界的劳动。',
    color: '#2dd4bf'
  },
  {
    id: 'lianzhen',
    name: '廉贞',
    pinyin: 'Lian Zhen',
    category: StarCategory.MAIN,
    realm: LacanRealm.SYMBOLIC,
    lacanConcept: '欲望与禁忌的张力',
    description: '超我的严苛与欲望的放逐在象征秩序边缘的博弈。',
    traditionalMeaning: '囚星，邪星，纪律，次桃花。',
    philosophicalInsight: '廉贞展示了象征秩序如何通过禁忌（囚）来维持欲望的生命力。',
    color: '#ef4444'
  },
  {
    id: 'tianfu',
    name: '天府',
    pinyin: 'Tian Fu',
    category: StarCategory.MAIN,
    realm: LacanRealm.IMAGINARY,
    lacanConcept: '自我的容器',
    description: '稳固的防御机制，试图通过积累来填补本体论的空洞。',
    traditionalMeaning: '库房，稳重，包容，代表守成。',
    philosophicalInsight: '天府是自我（Ego）构建的避风港，用符号资产抵御虚无。',
    color: '#f97316'
  },
  {
    id: 'taiyin',
    name: '太阴',
    pinyin: 'Tai Yin',
    category: StarCategory.MAIN,
    realm: LacanRealm.IMAGINARY,
    lacanConcept: '幻想空间 (Phantasy)',
    description: '私密的、柔和的映射，为主体提供栖息的幻景。',
    traditionalMeaning: '母性，宁静，田宅，代表潜意识中的安全感。',
    philosophicalInsight: '太阴是那面能映出温情的魔镜，它是主体避开实在界恐怖的屏幕。',
    color: '#818cf8'
  },
  {
    id: 'tanlang',
    name: '贪狼',
    pinyin: 'Tan Lang',
    category: StarCategory.MAIN,
    realm: LacanRealm.IMAGINARY,
    lacanConcept: '小客体a (Objet Petit a)',
    description: '欲望的诱因，那永远无法企及的、在缺失处闪烁的对象。',
    traditionalMeaning: '桃花，贪欲，修道，代表生命的原动力。',
    philosophicalInsight: '贪狼不代表欲望的对象，而代表欲望本身作为动力的“匮乏”。',
    color: '#ec4899'
  },
  {
    id: 'jumen',
    name: '巨门',
    pinyin: 'Ju Men',
    category: StarCategory.MAIN,
    realm: LacanRealm.REAL,
    lacanConcept: '能指的深渊 (The Abyss of the Signifier)',
    description: '言语无法填补的空穴，是焦虑与怀疑的源头。',
    traditionalMeaning: '暗星，口舌，疑虑，代表不可言说之物。',
    philosophicalInsight: '巨门是实在界的入侵，是象征秩序中那道“漏气”的裂缝。',
    color: '#4b5563'
  },
  {
    id: 'tianxiang',
    name: '天相',
    pinyin: 'Tian Xiang',
    category: StarCategory.MAIN,
    realm: LacanRealm.SYMBOLIC,
    lacanConcept: '镜像识别与契约',
    description: '辅助权威的官样文章，是象征秩序得以契合的胶水。',
    traditionalMeaning: '印星，协调，文书，代表公正与形式感。',
    philosophicalInsight: '天相通过形式的完美（印章），试图掩盖结构性的缺陷。',
    color: '#06b6d4'
  },
  {
    id: 'tianliang',
    name: '天梁',
    pinyin: 'Tian Liang',
    category: StarCategory.MAIN,
    realm: LacanRealm.SYMBOLIC,
    lacanConcept: '超我的父性保护',
    description: '通过建立道德律法与牺牲来缓解主体的原罪感。',
    traditionalMeaning: '荫星，老人，纪律，代表保护与解厄。',
    philosophicalInsight: '天梁是文明赋予个体的道德屏障，是象征秩序的柔性监护。',
    color: '#84cc16'
  },
  {
    id: 'qisha',
    name: '七杀',
    pinyin: 'Qi Sha',
    category: StarCategory.MAIN,
    realm: LacanRealm.REAL,
    lacanConcept: '死驱力 (Death Drive)',
    description: '对象征秩序的毁灭性突破，直接面对生命的荒诞真相。',
    traditionalMeaning: '将星，肃杀，变革，代表不破不立。',
    philosophicalInsight: '七杀是主体抛弃所有象征面具，直面“它者不存在”的瞬间。',
    color: '#b91c1c'
  },
  {
    id: 'pojun',
    name: '破军',
    pinyin: 'Po Jun',
    category: StarCategory.MAIN,
    realm: LacanRealm.REAL,
    lacanConcept: '付诸行动 (Passage to the Act)',
    description: '通过彻底的耗散与破坏来否定象征界的统治。',
    traditionalMeaning: '耗星，先锋，重建，代表彻底的变革。',
    philosophicalInsight: '破军是以主体的自我湮灭为代价，向实在界发起的主动进攻。',
    color: '#1e3a8a'
  },

  // --- 14 Assistant Stars (十四辅星) ---
  {
    id: 'zuofu',
    name: '左辅',
    pinyin: 'Zuo Fu',
    category: StarCategory.ASSISTANT,
    realm: LacanRealm.IMAGINARY,
    lacanConcept: '镜像认同 (Specular Identification)',
    description: '来自同伴的支持，强化自我的虚幻统一感。',
    traditionalMeaning: '平辈助力，稳健。',
    philosophicalInsight: '左辅修补了主体初期的支离破碎感。',
    color: '#a5f3fc'
  },
  {
    id: 'youbi',
    name: '右弼',
    pinyin: 'You Bi',
    category: StarCategory.ASSISTANT,
    realm: LacanRealm.IMAGINARY,
    lacanConcept: '自我理想的投射',
    description: '对自我能力延伸的幻想性肯定。',
    traditionalMeaning: '异性助力，机智。',
    philosophicalInsight: '右弼是自我在其社交网络中投射出的辅助性幻象。',
    color: '#a78bfa'
  },
  {
    id: 'wenchang',
    name: '文昌',
    pinyin: 'Wen Chang',
    category: StarCategory.ASSISTANT,
    realm: LacanRealm.SYMBOLIC,
    lacanConcept: '主人能指 (S1)',
    description: '被赋予权威的文字与律法。',
    traditionalMeaning: '科甲，文书。',
    philosophicalInsight: '文昌是进入象征界的入场券。',
    color: '#60a5fa'
  },
  {
    id: 'wenqu',
    name: '文曲',
    pinyin: 'Wen Qu',
    category: StarCategory.ASSISTANT,
    realm: LacanRealm.SYMBOLIC,
    lacanConcept: '知识的享乐 (S2)',
    description: '能指链条中的韵律与感性知识。',
    traditionalMeaning: '才艺，口才。',
    philosophicalInsight: '文曲是理性的诗意化表达。',
    color: '#34d399'
  },
  {
    id: 'tiankui',
    name: '天魁',
    pinyin: 'Tian Kui',
    category: StarCategory.ASSISTANT,
    realm: LacanRealm.SYMBOLIC,
    lacanConcept: '理想它者 (Ideal Other)',
    description: '象征秩序中仁慈的引导力量。',
    traditionalMeaning: '贵人，明助。',
    philosophicalInsight: '天魁是潜意识中对全知全能且仁慈的父性的渴望。',
    color: '#fbbf24'
  },
  {
    id: 'tianyue',
    name: '天钺',
    pinyin: 'Tian Yue',
    category: StarCategory.ASSISTANT,
    realm: LacanRealm.SYMBOLIC,
    lacanConcept: '象征界的机遇',
    description: '在象征秩序缝隙中闪现的机会。',
    traditionalMeaning: '贵人，暗助。',
    philosophicalInsight: '天钺是象征界对主体的偶然奖赏。',
    color: '#f472b6'
  },
  {
    id: 'qingyang',
    name: '擎羊',
    pinyin: 'Qing Yang',
    category: StarCategory.ASSISTANT,
    realm: LacanRealm.REAL,
    lacanConcept: '阉割之刃 (Castration)',
    description: '进入象征界必须付出的创伤性代价。',
    traditionalMeaning: '刑伤，冲动。',
    philosophicalInsight: '擎羊是划开主体与原初享乐的致命一刀。',
    color: '#dc2626'
  },
  {
    id: 'tuoluo',
    name: '陀罗',
    pinyin: 'Tuo Luo',
    category: StarCategory.ASSISTANT,
    realm: LacanRealm.REAL,
    lacanConcept: '症状的螺旋',
    description: '主体在创伤周围不断的重复循环。',
    traditionalMeaning: '拖延，阻碍。',
    philosophicalInsight: '陀罗是死驱力在象征界的一种体现。',
    color: '#64748b'
  },
  {
    id: 'huoxing',
    name: '火星',
    pinyin: 'Huo Xing',
    category: StarCategory.ASSISTANT,
    realm: LacanRealm.REAL,
    lacanConcept: '享乐的爆发',
    description: '不可控的情绪与原始能量喷发。',
    traditionalMeaning: '暴躁，动荡。',
    philosophicalInsight: '火星是主体瞬间失去对语言控制的时刻。',
    color: '#f97316'
  },
  {
    id: 'lingxing',
    name: '铃星',
    pinyin: 'Ling Xing',
    category: StarCategory.ASSISTANT,
    realm: LacanRealm.REAL,
    lacanConcept: '超我的回响',
    description: '隐秘的自我惩罚机制。',
    traditionalMeaning: '焦虑，隐患。',
    philosophicalInsight: '铃星是超我那永不停息的、尖锐的指责。',
    color: '#4338ca'
  },
  {
    id: 'dikong',
    name: '地空',
    pinyin: 'Di Kong',
    category: StarCategory.ASSISTANT,
    realm: LacanRealm.REAL,
    lacanConcept: '原初匮乏 (The Void)',
    description: '主体核心处的那个结构性黑洞。',
    traditionalMeaning: '空亡，消解。',
    philosophicalInsight: '地空揭示了欲望的核心并非任何对象，而是空无。',
    color: '#0f172a'
  },
  {
    id: 'dijie',
    name: '地劫',
    pinyin: 'Di Jie',
    category: StarCategory.ASSISTANT,
    realm: LacanRealm.REAL,
    lacanConcept: '欲望的截断 (Interruption)',
    description: '对幻想屏幕的粗暴撕裂。',
    traditionalMeaning: '破财，波折。',
    philosophicalInsight: '地劫是突然遭遇“它者并不存在”的瞬间。',
    color: '#451a03'
  },
  {
    id: 'lucun',
    name: '禄存',
    pinyin: 'Lu Cun',
    category: StarCategory.ASSISTANT,
    realm: LacanRealm.IMAGINARY,
    lacanConcept: '剩余享乐 (Plus-de-jouir)',
    description: '支撑主体平衡的那点盈余。',
    traditionalMeaning: '财禄，稳固。',
    philosophicalInsight: '禄存是主体试图抓住的维持平衡的“多余”。',
    color: '#fb7185'
  },
  {
    id: 'tianma',
    name: '天马',
    pinyin: 'Tian Ma',
    category: StarCategory.ASSISTANT,
    realm: LacanRealm.SYMBOLIC,
    lacanConcept: '转喻的运动',
    description: '欲望从一个能指跳跃到另一个能指的过程。',
    traditionalMeaning: '奔波，变动。',
    philosophicalInsight: '天马是欲望的引擎，永远在位移中。',
    color: '#fbbf24'
  },

  // --- 37 Miscellaneous Stars (三十七杂曜 - Selection) ---
  {
    id: 'hongluan',
    name: '红鸾',
    pinyin: 'Hong Luan',
    category: StarCategory.MISC,
    realm: LacanRealm.IMAGINARY,
    lacanConcept: '镜像的绽放',
    description: '镜像阶段中对“美”的初次捕获。',
    traditionalMeaning: '婚配，喜庆，人缘。',
    philosophicalInsight: '红鸾是主体在它者目光中构建出的最迷人的幻象。',
    color: '#fda4af'
  },
  {
    id: 'tianxi',
    name: '天喜',
    pinyin: 'Tian Xi',
    category: StarCategory.MISC,
    realm: LacanRealm.IMAGINARY,
    lacanConcept: '享乐的火花',
    description: '瞬间的、爆发式的快感体验。',
    traditionalMeaning: '开心，喜事，冲喜。',
    philosophicalInsight: '天喜是主体在象征秩序的重压下偶然获得的呼吸孔。',
    color: '#fca5a5'
  },
  {
    id: 'tianxing',
    name: '天刑',
    pinyin: '天刑',
    category: StarCategory.MISC,
    realm: LacanRealm.SYMBOLIC,
    lacanConcept: '被划杠的主体 ($)',
    description: '法律对欲望的直接干预与惩戒。',
    traditionalMeaning: '孤克，刑法，手术，官司。',
    philosophicalInsight: '天刑是象征秩序中那道冰冷的“不准”。',
    color: '#475569'
  },
  {
    id: 'tianyao',
    name: '天姚',
    pinyin: 'Tian Yao',
    category: StarCategory.MISC,
    realm: LacanRealm.IMAGINARY,
    lacanConcept: '假面 (Semblant)',
    description: '一种诱惑性的表演，旨在掩盖内在的空洞。',
    traditionalMeaning: '风流，姿色，隐秘的欲望。',
    philosophicalInsight: '天姚通过符号化的装饰来填充欲望的缺口。',
    color: '#d946ef'
  },
  {
    id: 'santai',
    name: '三台',
    pinyin: 'San Tai',
    category: StarCategory.MISC,
    realm: LacanRealm.SYMBOLIC,
    lacanConcept: '象征界的阶梯',
    description: '通过社会地位获得的虚假完整感。',
    traditionalMeaning: '地位，辅佐。',
    philosophicalInsight: '三台是主体在象征金字塔中攀爬的幻觉。',
    color: '#93c5fd'
  },
  {
    id: 'bazuo',
    name: '八座',
    pinyin: 'Ba Zuo',
    category: StarCategory.MISC,
    realm: LacanRealm.SYMBOLIC,
    lacanConcept: '它者的宝座',
    description: '认同大它者的位置以获得稳定性。',
    traditionalMeaning: '威望，名声。',
    philosophicalInsight: '八座是主体试图在它者的结构中坐稳那个“位置”。',
    color: '#bfdbfe'
  },
  {
    id: 'enguang',
    name: '恩光',
    pinyin: 'En Guang',
    category: StarCategory.MISC,
    realm: LacanRealm.SYMBOLIC,
    lacanConcept: '大它者的凝视 (The Gaze)',
    description: '被它者认可时所感受到的“光荣”。',
    traditionalMeaning: '殊荣，被提拔。',
    philosophicalInsight: '恩光是主体的自我通过它者的目光获得的非法享乐。',
    color: '#e9d5ff'
  },
  {
    id: 'tiangui',
    name: '天贵',
    pinyin: 'Tian Gui',
    category: StarCategory.MISC,
    realm: LacanRealm.SYMBOLIC,
    lacanConcept: '象征的价值',
    description: '在符号系统中被赋予的高贵权重。',
    traditionalMeaning: '贵气，诚信。',
    philosophicalInsight: '天贵是将肉体凡胎转化为“尊贵符号”的炼金术。',
    color: '#ddd6fe'
  },
  {
    id: 'longchi',
    name: '龙池',
    pinyin: 'Long Chi',
    category: StarCategory.MISC,
    realm: LacanRealm.IMAGINARY,
    lacanConcept: '审美的升华',
    description: '通过艺术形式来缓解实在界的焦虑。',
    traditionalMeaning: '才艺，住宅。',
    philosophicalInsight: '龙池是主体为自己挖掘的盛放情感的华丽池沼。',
    color: '#99f6e4'
  },
  {
    id: 'fengge',
    name: '凤阁',
    pinyin: 'Feng Ge',
    category: StarCategory.MISC,
    realm: LacanRealm.SYMBOLIC,
    lacanConcept: '能指的优雅',
    description: '言语修辞的精致化，是社交的外壳。',
    traditionalMeaning: '名望，美感。',
    philosophicalInsight: '凤阁是象征界中那层最美丽的包装纸。',
    color: '#ccfbf1'
  },
  {
    id: 'yinsha',
    name: '阴煞',
    pinyin: 'Yin Sha',
    category: StarCategory.MISC,
    realm: LacanRealm.REAL,
    lacanConcept: '诡异 (The Uncanny)',
    description: '熟悉之物中的陌生感，实在界的鬼魅入侵。',
    traditionalMeaning: '邪祟，小人，心理阴影。',
    philosophicalInsight: '阴煞是潜意识中那份无法言说的、令人不安的真相。',
    color: '#1e293b'
  },
  {
    id: 'huagai',
    name: '华盖',
    pinyin: 'Hua Gai',
    category: StarCategory.MISC,
    realm: LacanRealm.IMAGINARY,
    lacanConcept: '孤独的华服',
    description: '通过自我孤立来维持自恋的完整。',
    traditionalMeaning: '才华，孤独，宗教。',
    philosophicalInsight: '华盖是主体为自己打造的、防止它者入侵的象牙塔。',
    color: '#fef3c7'
  },
  {
    id: 'xianchi',
    name: '咸池',
    pinyin: 'Xian Chi',
    category: StarCategory.MISC,
    realm: LacanRealm.IMAGINARY,
    lacanConcept: '肉身的泥沼',
    description: '沉溺于感官享乐而导致的自我丧失。',
    traditionalMeaning: '肉欲，烂桃花。',
    philosophicalInsight: '咸池是欲望在想象界中最原始、最浑浊的沉淀。',
    color: '#be123c'
  },
  {
    id: 'guchen',
    name: '孤辰',
    pinyin: 'Gu Chen',
    category: StarCategory.MISC,
    realm: LacanRealm.REAL,
    lacanConcept: '主体的荒凉',
    description: '剥离所有社交关系后的纯粹孤独。',
    traditionalMeaning: '孤僻，克男亲。',
    philosophicalInsight: '孤辰是主体面对自己是一堆“无意义碎屑”的真相。',
    color: '#52525b'
  },
  {
    id: 'guasu',
    name: '寡宿',
    pinyin: 'Gua Su',
    category: StarCategory.MISC,
    realm: LacanRealm.REAL,
    lacanConcept: '配偶的缺失',
    description: '对他者互补性幻想的彻底破灭。',
    traditionalMeaning: '寂寞，克女亲。',
    philosophicalInsight: '寡宿揭示了“性关系不存在”的拉康命题。',
    color: '#3f3f46'
  },
  {
    id: 'feilian',
    name: '蜚廉',
    pinyin: 'Fei Lian',
    category: StarCategory.MISC,
    realm: LacanRealm.SYMBOLIC,
    lacanConcept: '恶毒的流言',
    description: '被外部能指恶意定义的创伤。',
    traditionalMeaning: '流言，孤独。',
    philosophicalInsight: '蜚廉是它者的语言对主体发起的无端攻击。',
    color: '#78350f'
  },
  {
    id: 'posui',
    name: '破碎',
    pinyin: 'Po Sui',
    category: StarCategory.MISC,
    realm: LacanRealm.REAL,
    lacanConcept: '支离破碎的身体',
    description: '镜像阶段之前的身体经验。',
    traditionalMeaning: '残缺，不顺，破财。',
    philosophicalInsight: '破碎是主体统一性幻象下潜藏的恐怖碎片。',
    color: '#450a0a'
  },
  {
    id: 'tianwu',
    name: '天巫',
    pinyin: 'Tian Wu',
    category: StarCategory.MISC,
    realm: LacanRealm.SYMBOLIC,
    lacanConcept: '无意识的知识',
    description: '关于命运、潜意识和符号规律的洞察。',
    traditionalMeaning: '遗产，玄学，直觉。',
    philosophicalInsight: '天巫是主体试图解读大它者“代码”的尝试。',
    color: '#4c1d95'
  },
  {
    id: 'tianshou',
    name: '天寿',
    pinyin: 'Tian Shou',
    category: StarCategory.MISC,
    realm: LacanRealm.REAL,
    lacanConcept: '驱力的顽强',
    description: '生命力在死亡阴影下的持续运作。',
    traditionalMeaning: '长寿，宽厚。',
    philosophicalInsight: '天寿是生命作为一种“盈余”在实在界中的持续存在。',
    color: '#064e3b'
  }
];
